# Generated by Django 4.2.5 on 2023-09-25 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('send_location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
