# Generated by Django 4.2.5 on 2023-09-27 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_location', '0002_location_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('unique_id', models.IntegerField(unique=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('last_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_position', to='send_location.location')),
            ],
        ),
    ]
