# Generated by Django 4.2.5 on 2023-10-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_location', '0004_device_lat_device_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='device',
            name='lon',
        ),
    ]
